apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-lab
  template:
    metadata:
      labels:
        app: kube-lab-broken   # temporary typo
    spec:
      containers:
        - name: kube-lab-container
          image: kube-lab-app:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: kube-lab-mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              value: library
            - name: REDIS_HOST
              value: kube-lab-redis
            - name: REDIS_PORT
              value: "6379"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
