apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-lab-redis
  template:
    metadata:
      labels:
        app: kube-lab-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-lab-redis
spec:
  selector:
    app: kube-lab-redis
  ports:
    - port: 6379
      targetPort: 6379
